trigger:
  branches:
    include:
      - main
pool:
  name: 'Default'
variables:
  buildConfiguration: 'Release'
  packageName: 'HelloWorldApp'
  feedName: 'New_Hello_World'
  projectName: 'Hello_World_pipeline'
  packageVersion: '1.0.$(Build.BuildId)'  # Dynamic version using Build ID
  sonarQubeServiceConnection: 'SonarQube_Connection'  # Replace with your service connection name
  sonarQubeProjectKey: 'Hello_World_pipeline_Hello_World_pipeline_5439e27a-7696-4cc6-a3f9-16f0e5155ba0'  # Replace with your SonarQube project key
  sonarQubeProjectName: 'Hello_World_pipeline'  # Replace with your SonarQube project name
  sonarQubeUrl: 'http://51.20.116.107:9000'  # Replace with your SonarQube server URL

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the Project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: SonarQubePrepare@6  # Updated task version if available
  displayName: 'Prepare analysis on SonarQube'
  inputs:
    SonarQube: '$(sonarQubeServiceConnection)'
    scannerMode: 'CLI'
    configMode: 'manual'
    projectKey: 'Hello_World_pipeline_Hello_World_pipeline_5439e27a-7696-4cc6-a3f9-16f0e5155ba0'
    projectName: '$(sonarQubeProjectName)'
    projectVersion: '$(packageVersion)'
    sources: '.'
    extraProperties: |
      sonar.host.url=$(sonarQubeUrl)
      sonar.cs.vs.project=HelloWorldApp  # Update as per your project structure

# Use SonarQubeAnalyze instead of SonarQubeRun
- task: SonarQubeAnalyze@6  # Updated task version if available
  displayName: 'Run SonarQube analysis'

- task: DotNetCoreCLI@2
  displayName: 'Pack the Project'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.SourcesDirectory)/nuget_output /p:PackageId=$(packageName) /p:Version=$(packageVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(projectName)/$(feedName)'
    arguments: '--skip-duplicate'

