trigger:
  branches:
    include:
      - main
pool:
  name: 'Default'
variables:
  buildConfiguration: 'Release'
  packageName: 'HelloWorldApp'
  feedName: 'New_Hello_World'
  projectName: 'Hello_World_pipeline'
  packageVersion: '1.0.0'  # Fixed version

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the Project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack the Project'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.SourcesDirectory)/nuget_output /p:PackageId=$(packageName) /p:Version=$(packageVersion)'


- script: |
    echo "Listing all files in the nuget_output directory before push:"
    ls -R $(Build.SourcesDirectory)/nuget_output
  displayName: 'List NuGet Output Files'
  
- script: |
    echo "Package Version: $(packageVersion)"
    echo "Build ID: $(Build.BuildId)"
  displayName: 'Echo Package Version'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(projectName)/$(feedName)'
    arguments: '--skip-duplicate'
