trigger:
  branches:
    include:
      - main
pool:
  name: 'Default'
variables:
  buildConfiguration: 'Release'
  packageName: 'HelloWorldApp'
  feedName: 'New_Hello_World'
  projectName: 'Hello_World_pipeline'
  packageVersion: '1.0.$(Build.BuildId)'  # Dynamic version using Build ID
  sonarProjectKey: 'Hello_World_pipeline_Hello_World_pipeline_5439e27a-7696-4cc6-a3f9-16f0e5155ba0'        # Replace with your project key
  sonarProjectName: 'Hello_World_pipeline'     # Replace with your project name
  sonarProjectVersion: '1.0'              # Replace with your project version

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'SonarQubeServiceConnection'  # Service connection name created earlier
    scannerMode: 'MSBuild'
    projectKey: '$(sonarProjectKey)'
    projectName: '$(sonarProjectName)'
    projectVersion: '$(sonarProjectVersion)'
    # Ensure branch-related properties are not included

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the Project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube Analysis'

- task: DotNetCoreCLI@2
  displayName: 'Pack the Project'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.SourcesDirectory)/nuget_output /p:PackageId=$(packageName) /p:Version=$(packageVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(projectName)/$(feedName)'
    arguments: '--skip-duplicate'

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'

