trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  packageName: 'HelloWorldApp'
  sonarQubeServiceConnection: 'SonarQube_Connection'
  sonarQubeProjectKey: 'Hello_World_pipeline'
  sonarQubeProjectName: 'Hello_World_pipeline'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: SonarQubePrepare@5
  displayName: 'Prepare SonarQube Analysis'
  inputs:
    SonarQube: '$(sonarQubeServiceConnection)'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(sonarQubeProjectKey)'
    cliProjectName: '$(sonarQubeProjectName)'
    cliSources: '.'
    extraProperties: |
      sonar.qualitygate.wait=true
      sonar.verbose=true
   


- task: DotNetCoreCLI@2
  displayName: 'Build the Project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube analysis'

- task: SonarQubePublish@5
  displayName: 'Publish SonarQube Results'

- task: DotNetCoreCLI@2
  displayName: 'Pack the Project'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.SourcesDirectory)/nuget_output /p:PackageId=$(packageName) /p:Version=$(packageVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(projectName)/$(feedName)'
    arguments: '--skip-duplicate'

